### ISSUE TITLE
Document common TinyMCE integrations

### ISSUE THREAD

**Issue by danielbachhuber** [danielbachhuber/gutenberg-migration-guide#1]
There are a variety of ways developers might be interacting with TinyMCE (button registration, content manipulation, etc.). We should get them documented.

**Comment by jcklpe** [comment]
I'm a super newbie developer and I haven't delved into anything past theming yet, but are there ways I can contribute to this? Would it be helpful for me to log information on the ways I use tinyMCE plugins or something like that?

**Comment by danielbachhuber** [comment]
> I'm a super newbie developer and I haven't delved into anything past theming yet, but are there ways I can contribute to this?

Maybe! What would be helpful is if you signed up for the [Gutenberg Plugin Compatibility Database](https://plugincompat.danielbachhuber.com/) and helped test plugins. I've been [using that data](https://danielbachhuber.com/2018/04/25/summary-of-gutenberg-plugin-compatibility-database-results-to-date/) to determine the biggest problem points for incompatibility.

**Comment by thedonquixotic** [comment]
Awesome and done! Excited to try some of these plugins on my website.

**Comment by jcklpe** [comment]
Awesome! And will do. I'll log all the plugins I'm using.

**Comment by danielbachhuber** [comment]
TinyMCE integration point documentation is a work-in-progress: https://github.com/danielbachhuber/gutenberg-migration-guide#tinymce
