### ISSUE TITLE
TinyMCE styleselect

### ISSUE THREAD

**Issue by mrwweb** [danielbachhuber/gutenberg-migration-guide#10]
The TinyMCE styleselect is a way to define wrapping markup or classes to all or specific elements in the editor. For reference here is the [TinyMCE](https://www.tiny.cloud/docs/configure/content-formatting/#style_formats) and [WordPress](https://codex.wordpress.org/TinyMCE_Custom_Styles#Enabling_styleselect) documentation for using the feature.

It appears that this function will continue working in the Classic Editor block, but I think documenting the overlap of it and Gutenberg may be useful and appropriate for this guide. The ability to set wrapping markup is a defining feature of blocks and the ability to add classes is now often covered by the [new style variant feature](https://github.com/WordPress/gutenberg/pull/7362) in Gutenberg which allows defining and applying CSS classes to blocks.

**Comment by danielbachhuber** [comment]
@mrwweb Do you want to submit a pull request against https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/tinymce-filters.md with suggested changes?

**Comment by danielbachhuber** [comment]
Documented with https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/tinymce-style-formats.md
