### ISSUE TITLE
The hook for editor.PostFeaturedImage is not executed

### ISSUE THREAD

**Issue by Sisanu** [danielbachhuber/gutenberg-migration-guide#11]
Hello!
I have been following all the discussions about the removal of the `admin_post_thumbnail_html` and the alternative for Gutenberg, however, for the latest version, the hooks just do not trigger.

I am referring to `wp.hooks.addFilter( 'editor.PostFeaturedImage', ...`
Is there some functional example available (the examples provided at https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/filter-admin-post-thumbnail-html.md are not working) or a known issue with these?

Thank you!

**Comment by danielbachhuber** [comment]
👋 Thanks for the report, @Sisanu.

The filter exists on the Gutenberg `master` branch, but hasn't been released yet. I've updated the docs accordingly 19fdea6
