### ISSUE TITLE
Custom Inline markup for my themes

### ISSUE THREAD

**Issue by bluisier** [danielbachhuber/gutenberg-migration-guide#12]
I'm using `mce_buttons_2` and `tiny_mce_before_init` to add custom inline markup easily in my posts (custom mark or span tags, or custom classes for links). I tried to extend the paragraph block as mentioned in [4658](https://github.com/WordPress/gutenberg/issues/4658) without success for the moment.
![screenshot from 2018-09-05 15-35-14](https://user-images.githubusercontent.com/15941266/45097398-163f0280-b123-11e8-9ae2-1e9c66d3a417.png)

**Comment by danielbachhuber** [comment]
Hi @bluisier,

Thanks for the report.

> I'm using `mce_buttons_2` and `tiny_mce_before_init` to add custom inline markup easily in my posts (custom mark or span tags, or custom classes for links).

Can you share the existing code you're using for this? Also, which [reference point](https://github.com/danielbachhuber/gutenberg-migration-guide#actions--filters) do you think it would be helpful to include with?

**Comment by bluisier** [comment]
Hi @danielbachhuber ,
here is the code I'm using for this : 
```
add_filter( 'mce_buttons_2', __NAMESPACE__ . '\add_style_select_buttons' );

function add_style_select_buttons( $buttons ) {
	array_unshift( $buttons, 'styleselect' );
	return $buttons;
}

add_filter( 'tiny_mce_before_init', __NAMESPACE__ . '\my_custom_styles' );

function my_custom_styles( $init_array ) {

	$style_formats = array(
		// These are the custom styles
		array(
			'title' => 'mark',
			'inline' => 'mark',
			'wrapper' => true,
		),
		array(
			'title' => 'mark citation',
			'inline' => 'mark',
			'classes' => 'citation',
			'wrapper' => true,
		),
		array(
			'title' => 'mark question',
			'inline' => 'mark',
			'classes' => 'question',
			'wrapper' => true,
		),
		array(
			'title' => 'infos',
			'block' => 'div',
			'classes' => 'infos',
			'wrapper' => true,
		),
		array(
			'title' => 'infos titre',
			'inline' => 'span',
			'classes' => 'infos-titre',
			'wrapper' => true,
		),
		array(
			'title' => 'infos liste',
			'selector' => 'ul',
			'classes' => 'infos-liste',
		),
		array(
			'title' => 'infos sous titre',
			'inline' => 'span',
			'classes' => 'infos-sous-titre',
			'wrapper' => true,
		),
		array(
			'title' => 'lien affilié',
			'selector' => 'a',
			'classes' => 'affiliate',
		),
		array(
			'title' => 'lien boutton',
			'selector' => 'a',
			'classes' => 'link-button',
		),
		array(
			'title' => 'box blanche',
			'block' => 'div',
			'classes' => 'white-box',
			'wrapper' => true,
		),
	);
	// Insert the array, JSON ENCODED, into 'style_formats'
	$init_array['style_formats'] = json_encode( $style_formats );

	return $init_array;

}
```
This way it is very easy to add inline custom markup with custom classes. With `wrapper` it is also very easy to add custom classes to existing markup (for links for example) without editing the html. It would be really nice to have smth like this in gutenberg as mentioned in [4658](https://github.com/WordPress/gutenberg/issues/4658).
I guess you can include this under TinyMCE Filters

**Comment by danielbachhuber** [comment]
Great. This is the same as #10

**Comment by danielbachhuber** [comment]
Documented with https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/tinymce-style-formats.md

Thanks again for opening the issue, @bluisier
