### ISSUE TITLE
Example of "post_gallery" filter

### ISSUE THREAD

**Issue by tyrann0us** [danielbachhuber/gutenberg-migration-guide#16]
>Please [open a new issue](/danielbachhuber/gutenberg-migration-guide/issues) to suggest additional examples of existing usage.
>&mdash; [Post Gallery Filter](https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/filter-post-gallery.md)

The plugin [Slick Slider](https://wordpress.org/plugins/slick-slider/) (https://github.com/tyrann0us/slick-slider) uses the `post_gallery` filter to turn native galleries into sliders:
https://github.com/tyrann0us/slick-slider/blob/761477365a31a2947f65dd19e8ffbc818c0815d9/inc/class-output.php#L39-L47

Because of the missing filter the plugin ~does _not_ work with Gutenberg~ cannot simply re-use it for websites that use the Block Editor, but the code has to be rewritten to use `register_block_type()`'s `render_callback`.

Disclaimer: I'm the author of this plugin.

**Comment by danielbachhuber** [comment]
Thanks for the report, @tyrann0us! Want to submit a pull request against the README with your example?

**Comment by tyrann0us** [comment]
See #19.
