### ISSUE TITLE
Detect Editor Type

### ISSUE THREAD

**Issue by dmccan** [danielbachhuber/gutenberg-migration-guide#2]
I imagine many plugins will need to support the classic editor and Gutenberg. So, it would be helpful if the guild showed how to detect if on the edit screen we are using the classic editor or Gutenberg.

Thanks

**Comment by danielbachhuber** [comment]
Thanks for the suggestion! Can you provide an example of how this detection API might be used?

**Comment by dmccan** [comment]
Yes, I should have done that ...

When we're on an editor page that uses the classic editor, I want to register a tinymce button, but when I'm on a page with Gutenberg I want to register a block. 

Another example is a link to an post (CPT wiki article), if the post doesn't exist we fill in the post title with the value from the link.  That will be done differently in Gutenberg. 

So I have a routine to detect if we're on the editor page ... I'll need to add some path in the code to handle the two editors differently.

**Comment by Venutius** [comment]
My use case is that I have a plugin that detects if a duplicate title is being used and it prevents the post from being published. Currently I can't see how to implement this in Gutenberg so I would like to disable this function if Gutenberg is being used, however we could have situations where Gutenberg is being used for posts, but not for CPT's so I would need a way of knowing which editor is being used so I can enabled or disable the required functionality.

**Comment by danielbachhuber** [comment]
Thanks folks. I think a better place for this request is the Gutenberg issue backlog itself: https://github.com/wordpress/gutenberg/issues
