### ISSUE TITLE
Media Tab Support

### ISSUE THREAD

**Issue by karamusluk** [danielbachhuber/gutenberg-migration-guide#21]
Hi @danielbachhuber ,

Does wordpress have any improvements about the https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/feature-media-tabs.md ? 

Since I am using this plugin to import videos to my system, I really need to update my Wordpress to support Gutenberg. Yet it is not supporting Custom Media Tab.

Could you assist me for this issue?

Thanks,
Mustafa

**Comment by danielbachhuber** [comment]
Hi @karamusluk,

> Does wordpress have any improvements about the https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/feature-media-tabs.md ?

Not to my knowledge, no. See https://github.com/WordPress/gutenberg/issues/6523

> Since I am using this plugin to import videos to my system, I really need to update my Wordpress to support Gutenberg. Yet it is not supporting Custom Media Tab.
> 
> Could you assist me for this issue?

Sorry, individual support is outside the scope of this repo.
