### ISSUE TITLE
Insert shortcode - not a block

### ISSUE THREAD

**Issue by dmccan** [danielbachhuber/gutenberg-migration-guide#3]
The current shortcode block inserts ... a block.  My plugin inserts a shortcode that is a link that should go inline within the content, not as a separate block. 

So that users don't have to remember the arcane shortcode syntax I have a button on the editor that pops up a modal. The picks from a dropdown and types in some text, and the shortcode gets inserted at the cursor location. I've seen a number of plugins that so similar. 

Thanks

**Comment by danielbachhuber** [comment]
Can you share which plugin you're referring to, and some screenshots or a GIF of the behavior you're referring to?

**Comment by dmccan** [comment]
Hi @danielbachhuber - Nice idea here. Thanks.

Yes, it is a simple wiki plugin:
https://github.com/dmccan/yada-wiki
https://wordpress.org/plugins/yada-wiki/

Here is a little video: https://cl.ly/462k2e2b0316

**Comment by Venutius** [comment]
I also have shortcodes that are intended to be inserted inline with the content. With the classic editor I provide a dropdown menu that alows for the shortcode to be inserted into the content. this shows in the Gutenberg classic block, however that block does not dynamically render the content, s it's not an ideal Gutenberg experience, though it's great that my menu is being shown. CodeDesign2 have produced a shortcode preview block - https://github.com/CODESIGN2/gutenberg-shortcode-preview-block and I've been asking about converting this into something that could be used with inline shortcodes, maybe with a RichText content field.

**Comment by danielbachhuber** [comment]
Thanks again @dmccan and @Venutius. I've [documented the button issue](https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/tinymce-toolbar-button.md).

> CodeDesign2 have produced a shortcode preview block - https://github.com/CODESIGN2/gutenberg-shortcode-preview-block and I've been asking about converting this into something that could be used with inline shortcodes, maybe with a RichText content field.

In this case, I think your best bet is converting your shortcode to a dynamic block, and then using Server-Side Render to preview it.
