### ISSUE TITLE
Add custom font to TinyMCE styles

### ISSUE THREAD

**Issue by TimVevida** [danielbachhuber/gutenberg-migration-guide#5]
Currently supported by using the `mce_css` filter, for example:

```
function my_tinymce_styles($style_string) {
	if (!empty($style_string)) {
		$style_string .= ',';
	}
	$style_string .= str_replace(',', '%2C', 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700');
	return $style_string;
}
add_filter('mce_css', 'my_tinymce_styles');
```

**Comment by danielbachhuber** [comment]
👍 Thanks for the report, @TimVevida !

**Comment by danielbachhuber** [comment]
@TimVevida I've [documented the resolution to this issue](https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/filter-mce-css.md). Let me know if you have any clarifying questions beyond this point.

**Comment by TimVevida** [comment]
Thank you for the documentation, it is very clear now.
