### ISSUE TITLE
Support for custom post statuses and custom mint publication actions

### ISSUE THREAD

**Issue by Venutius** [danielbachhuber/gutenberg-migration-guide#6]
I've written a plugin that uses IMath's wp_statuses to create new post statuses of Group Post, Members Only and Friends ?Only, to be used with BuddyPress networks. I've also added an additional notify fields and in the case of a group post there is a group selection drop down and a post visibility dropdown. So for Gutenberg I think we would need to replicate what Imath has done with wp_statuses for the standard editor. Currently I don't see how I could do that.

**Comment by danielbachhuber** [comment]
Hi @Venutius,

Thanks for the report. I've [documented this issue](https://github.com/danielbachhuber/gutenberg-migration-guide/blob/master/feature-custom-post-statuses.md) in the migration guide.
