### ISSUE TITLE
Will it be possible to insert inline content

### ISSUE THREAD

**Issue by dmccan** [danielbachhuber/gutenberg-migration-guide#7]
Hi @danielbachhuber, Thanks for trying to corral some issues. 

In relation to https://github.com/danielbachhuber/gutenberg-migration-guide/issues/3, is there a Guttenberg feature/issue that I should watch so I know when I can provide Gutenberg support or is this not something that will happen anytime soon?

**Comment by danielbachhuber** [comment]
> is there a Guttenberg feature/issue that I should watch so I know when I can provide Gutenberg support or is this not something that will happen anytime soon?

I'm not sure whether it will happen anytime soon. https://github.com/WordPress/gutenberg/issues/4658 is the best issue to watch for now.
