### ISSUE TITLE
Documentation of Filterable TinyMCE Settings?

### ISSUE THREAD

**Issue by mrwweb** [danielbachhuber/gutenberg-migration-guide#9]
As noted in WordPress/gutenberg#7942, there is at least one TinyMCE filterable setting that currently doesn't work in Gutenberg when using the Classic Editor block. I don't know if _all_ settings are ignored or if it's just that one. Either way, documenting `charmap_append` and potentially other settings that would appear to have Gutenberg equivalents (or should have) seems worthwhile.

**Comment by danielbachhuber** [comment]
👍 Thanks @mrwweb

**Comment by danielbachhuber** [comment]
> there is at least one TinyMCE filterable setting that currently doesn't work in Gutenberg when using the Classic Editor block.

I left a comment on your issue. I think that's a genuine bug that's best fixed in Gutenberg.

> Either way, documenting charmap_append and potentially other settings that would appear to have Gutenberg equivalents (or should have) seems worthwhile.

I've documented the TinyMCE filters in e97001d
